version: "3"
services:
  servlet:
    build: .
    ports:
        - "7777:8080"
    depends_on:
        - mysql-server

  mysql-server:
    image: mysql:latest
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: